name: mingw32-make

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: checkout code
      uses: actions/checkout@v4
      
    - name: Install MinGW 32-bit with Chocolatey
      run: choco install mingw
      
    - name: "Setup"
      run: |
        gcc --version
    
    - name: Compile Project
      run: |
        mingw32-make --version
        mingw32-make clean
        mingw32-make -m32 --debug
