name: mingw32-make

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: checkout code
      uses: actions/checkout@v4
      
    - name: Install MinGW with Chocolatey
      run: |
        choco install mingw -y
        refreshenv  # Refresh environment variables so the new MinGW path is recognized
        
    - name: Compile Project
      run: mingw32-make
