name: mingw32-make

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: checkout code
      uses: actions/checkout@v4
      
    - name: Install MinGW with Chocolatey
      run: |
        choco install mingw -y --x86

    - name: Add MinGW 32-bit to PATH
      shell: powershell
      run: |
        $mingwPath = "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw32\bin"
        echo "##[add-path]$mingwPath"
        
    - name: Compile Project
      run: mingw32-make
