name: mingw32-make

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: checkout code
      uses: actions/checkout@v4
      
    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x86
        version: 12.2.0 

    - name: "Setup"
      run: |
        gcc --version
    
    - name: Compile Project
      run: |
        mingw32-make --version
        mingw32-make clean
        mingw32-make --debug
        
    - name: Zip compiled file
      run: |
        zip bin/sfsf.zip bin/sfsf.asi  # Zip the compiled file in the 'bin' directory

    - name: Upload zipped artifact
      uses: actions/upload-artifact@v3
      with:
        name: sfsf-artifact
        path: bin/sfsf.zip 
